server: :443

tls:
  cert: /etc/hysteria/cert.pem
  key: /etc/hysteria/key.pem

auth:
  type: password
  password: Attomic2026!

masquerade:
  type: proxy
  proxy:
    url: https://attomic-production.up.railway.app
    rewriteHost: true

bandwidth:
  up: 1 gbps
  down: 1 gbps

disableUDP: false
