listen_addresses = ['127.0.0.1:53']
force_tcp = true

# فقط TCP - UDP غیرفعال
[listeners]
  [listeners.local_listener]
  tcp_only = true

server_names = ['cloudflare']

[static.'cloudflare']
stamp = 'sdns://AgcAAAAAAAAABzEuMC4wLjEAEmRucy5jbG91ZGZsYXJlLmNvbQovZG5zLXF1ZXJ5'
