listen_addresses = ['127.0.0.1:53']
force_tcp = true

server_names = ['cloudflare']

[static]
  [static.'cloudflare']
  stamp = 'sdns://AgcAAAAAAAAABzEuMC4wLjEAEmRucy5jbG91ZGZsYXJlLmNvbQovZG5zLXF1ZXJ5'

cache = true
log_level = 2
