load_module /usr/lib/nginx/modules/ngx_stream_module.so;

worker_processes auto;
pid /run/nginx.pid;

events {
    worker_connections 1024;
}

stream {
    server {
        listen 12130;
        proxy_pass 127.0.0.1:53;
        proxy_timeout 10s;
    }
}
