load_module /usr/lib/nginx/modules/ngx_stream_module.so;

worker_processes auto;
pid /run/nginx.pid;

events {
    worker_connections 1024;
}

stream {
    # TCP Proxy روی ۴۴۳
    server {
        listen 443;
        proxy_pass 127.0.0.1:53;
        proxy_timeout 10s;
    }
}

http {
    # Health check برای Railway
    server {
        listen 80;
        location / {
            return 200 'OK';
        }
    }
}
