[supervisord]
nodaemon=true
user=root
logfile=/var/log/supervisor/supervisord.log

[program:tor]
command=/usr/bin/tor -f /etc/tor/torrc
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stderr_logfile=/dev/stderr
