[supervisord]
nodaemon=true
user=root
logfile=/var/log/supervisor/supervisord.log

[program:debug]
command=/bin/sh -c "find / -name naive -type f && sleep 3600"
autostart=true
autorestart=false
stdout_logfile=/dev/stdout
stderr_logfile=/dev/stderr

[program:nginx]
command=nginx -g "daemon off;"
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stderr_logfile=/dev/stderr
