[supervisord]
nodaemon=true
user=root
logfile=/var/log/supervisor/supervisord.log

[program:dante]
command=/start.sh
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stderr_logfile=/dev/stderr

[program:websockify]
command=websockify 127.0.0.1:6080 127.0.0.1:1080
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stderr_logfile=/dev/stderr

[program:nginx]
command=nginx -g "daemon off;"
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stderr_logfile=/dev/stderr
